const newman = require('newman');

newman.run({
    collection: require('./data_postman/{COLLECTION_NAME}.postman_collection.json'), // can also provide a URL or path to a local JSON file.
    environment: require('./data_postman/{ENV_NAME}.postman_environment.json'), // Generated by postman
    reporters: 'htmlextra',
    reporter: {
        htmlextra: {
            export: './export/Report.html', // If not specified, the file will be written to `newman/` in the current working directory.,
            title: 'YOUR TITLE'
        }
    }
}, function (err) {
    if (err) { throw err; }
    console.log('collection run complete!');
});